linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US
  funlen:
    lines: 65
  varnamelen:
    min-name-length: 2
  tagliatelle:
    case:
      rules:
        json: snake
  ireturn:
    allow:
      - error
      - net\/http\.Handler
      - github\.com\/osamingo\/gosh\.JSONEncoder
  gosec:
    excludes:
      - G115

linters:
  enable-all: true
  disable:
    - depguard
