sudo: false

language: go
go:
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

before_script:
  - golangci-lint run

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
