codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

comment: off
